Repository pyymenta/spacecraft-cli, pull requests merged in 2020-10, with the labels that each got.

#12 Add pull request template
  .github/pull_request_template.md
  yarn.lock
Labels: enhancement

#14 Add a rocket image to README
  README.md
  rocket.jpg
Labels: enhancement

#18 update readme documentation
  README.md
Labels: documentation

#17 Rocket commands system, move and speed control
  dist/cli.js
  dist/cli.js.map
  dist/keyListener.js
  dist/keyListener.js.map
  dist/locations.js
  dist/locations.js.map
  dist/main.js
  dist/main.js.map
  dist/spacecraft.js
  dist/spacecraft.js.map
  package.json
  src/cli.ts
  src/keyListener.ts
  src/locations.ts
  src/main.ts
  src/spacecraft.ts
  tests/spacecraft.spec.ts
Labels: continuous-work, enhancement

#20 Fix async jest
  src/cli.ts
  tests/spacecraft.spec.ts
Labels: bug, continuous-work

#21 Add Travis CI to the Project
  .travis.yml
  README.md
Labels: continuous-work, documentation, enhancement

#36 Replace image with text
  README.md
Labels: documentation, enhancement

#32 feat: draw a rocket on cli initialization
  dist/cli.js
  dist/cli.js.map
  dist/keyListener.js
  dist/keyListener.js.map
  dist/locations.js
  dist/locations.js.map
  dist/main.js
  dist/main.js.map
  dist/rocket.js
  dist/rocket.js.map
  dist/spacecraft.js
  dist/spacecraft.js.map
  src/cli.ts
  src/rocket.ts
Labels: enhancement, hacktoberfest

#38 ADDITION: Contributor Guidelines
  contributor-guidelines.md
Labels: documentation

#34 Adding contributor list to README.md
  README.md
Labels: documentation

#47 Added demo gif
  README.md
  demo.gif
Labels: documentation, enhancement

#46 Documentation improvements
  README.md
Labels: documentation

#48 Clean Up Root Directory
  .gitignore
  README.md
  docs/contributor-guidelines.md
  images/demo.gif
  images/problem.png
  images/rocket.jpg
Labels: enhancement, hacktoberfest

#50 Publish npm package
  .npmignore
  bin/spacecraft-cli.js
  package.json
Labels: enhancement

#51 Add instructions how to run or install the CLI
  README.md
Labels: documentation

#53 Add npm badge
  README.md
Labels: documentation, enhancement

#33 Spacecraft sends notifications when certain events occur
  .tsconfig.json
  dist/cli.js
  dist/cli.js.map
  dist/events_messages.json
  dist/keyListener.js
  dist/keyListener.js.map
  dist/locations.js
  dist/locations.js.map
  dist/main.js
  dist/main.js.map
  dist/spacecraft.js
  dist/spacecraft.js.map
  dist/spacecraftEmitter.js
  dist/spacecraftEmitter.js.map
  jest.config.js
  package.json
  src/cli.ts
  src/main.ts
  src/spacecraft.ts
  src/spacecraftEmitter.ts
  tests/spacecraft.spec.ts
  tests/spacecraftEmitter.spec.ts
Labels: enhancement, hacktoberfest

#61 Fix lint issues
  bin/spacecraft-app-cli.js
  src/cli.ts
  src/spacecraft.ts
  src/spacecraftEmitter.ts
  tests/spacecraft.spec.ts
  tests/spacecraftEmitter.spec.ts
Labels: Maintenance

#62 Fix Rocket Initialization
  dist/cli.js
  dist/cli.js.map
  dist/keyListener.js
  dist/keyListener.js.map
  dist/locations.js
  dist/locations.js.map
  dist/main.js
  dist/main.js.map
  dist/rocket.js
  dist/rocket.js.map
  dist/spacecraft.js.map
  dist/spacecraftEmitter.js
  dist/spacecraftEmitter.js.map
  src/cli.ts
Labels: Maintenance, bug

#59 Add Jest code coverage and Travis CI configuration
  .travis.yml
  jest.config.js
Labels: Maintenance, continuous-work, enhancement, hacktoberfest

#58 eslintignore created with dist folder added
  .eslintignore
Labels: Maintenance

#56 Create .eslintignore
  .eslintignore
Labels: enhancement, hacktoberfest

#57 Improve tooling
  .DS_Store
  package.json
  src/cli.ts
  yarn.lock
Labels: continuous-work, enhancement, hacktoberfest

#65 Added Welcome Banner
  dist/cli.js
  dist/cli.js.map
  package-lock.json
  src/cli.ts
  src/welcome.ts
Labels: enhancement, hacktoberfest

#67 Update contributors guideline about branch syncing
  docs/contributor-guidelines.md
Labels: documentation

#64 feat: Add Help Command to CLI
  dist/cli.js
  dist/cli.js.map
  src/cli.ts
Labels: enhancement, hacktoberfest

#71 Added output to acknowledge invalid commands
  dist/cli.js
  dist/keyListener.js
  dist/keyListener.js.map
  src/keyListener.ts
Labels: enhancement, hacktoberfest
